#!/bin/zsh

echo "===========================start==========================="

function sum1 {
    return $[$1+$2+$3]
}

sum2(){
    return $[$1+$2]
}


sum1 12 23 300

echo "$?"
echo $[300 + 400]


